-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "address_line1" TEXT,
ADD COLUMN     "address_line2" TEXT,
ADD COLUMN     "bank_account_name" TEXT,
ADD COLUMN     "bank_account_number" TEXT,
ADD COLUMN     "bank_name" TEXT,
ADD COLUMN     "bank_sort_code" TEXT,
ADD COLUMN     "cis_number" TEXT,
ADD COLUMN     "cis_registered" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "county" TEXT,
ADD COLUMN     "default_invoice_notes" TEXT,
ADD COLUMN     "default_payment_terms" TEXT DEFAULT 'Payment due within 30 days',
ADD COLUMN     "default_vat_rate" DOUBLE PRECISION NOT NULL DEFAULT 20.0,
ADD COLUMN     "invoice_next_number" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "invoice_prefix" TEXT NOT NULL DEFAULT 'INV',
ADD COLUMN     "logo_url" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "postcode" TEXT,
ADD COLUMN     "vat_number" TEXT,
ADD COLUMN     "vat_registered" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "website" TEXT;
